#################################
## Rain alert message
#################################

Header      header
time        time
bool        rain_alert
int8        rain_now
string      status_past60m
string      status_past50m
string      status_past40m
string      status_past30m
string      status_past20m
string      status_past10m
string      status_now
string      status_nowcast10m
string      status_nowcast20m
string      status_nowcast30m
