#################################
## Weather forecast message
#################################

Header      header
time        time
string      summary
string      precip_type
float32     precip_intensity
float32     precip_probability
float32     precipAccumulation
float32     temperature
float32     dew_point
float32     humidity
float32     pressure
float32     wind_speed
float32     wind_gust
int16       wind_bearing
